import { MigrationInterface, QueryRunner } from 'typeorm';

export class createNotificationTable1634845072783
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    const query = `
    DROP TYPE IF EXISTS type_enum;
    CREATE TYPE type_enum AS ENUM('bad', 'good');
    
    CREATE TABLE notifications ( 
    id bigint generated by default as identity(start with 1) primary key,    
    user_id bigint NOT NULL,
    email VARCHAR(65) NOT NULL,
    phone VARCHAR(13),
    message VARCHAR(100),
    type type_enum,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
    `;

    await queryRunner.query(query);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
