import { MigrationInterface, QueryRunner } from 'typeorm';

export class createBillingTable1634845072783 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    const query = `
    DROP TYPE IF EXISTS event_enum;
    CREATE TYPE event_enum AS ENUM('refill', 'withdraw');
    
    CREATE TABLE billing ( 
    id bigint generated by default as identity(start with 1) primary key,    
    user_id bigint NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    event event_enum,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
    `;

    await queryRunner.query(query);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
